global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using Silk.NET.Core.Native;
global using Silk.NET.Vulkan;
global using RhiBuffer = SomeEngine.Graphics.Buffer;
global using RhiDevice = SomeEngine.Graphics.Device;
global using RhiFormat = SomeEngine.Graphics.Format;
global using RhiHeap = SomeEngine.Graphics.Heap;
global using RhiMemoryRequirements = SomeEngine.Graphics.MemoryRequirements;
global using RhiQueue = SomeEngine.Graphics.Queue;
global using RhiSampler = SomeEngine.Graphics.Sampler;
global using RhiSemaphore = SomeEngine.Graphics.ExternalTimeline;
global using RhiSurface = SomeEngine.Graphics.Surface;
global using RhiTexture = SomeEngine.Graphics.Texture;
global using VkBuffer = Silk.NET.Vulkan.Buffer;
global using VkAccelerationStructure = Silk.NET.Vulkan.AccelerationStructureKHR;
global using VkCommandBuffer = Silk.NET.Vulkan.CommandBuffer;
global using VkDevice = Silk.NET.Vulkan.Device;
global using VkDeviceMemory = Silk.NET.Vulkan.DeviceMemory;
global using VkDescriptorPool = Silk.NET.Vulkan.DescriptorPool;
global using VkDescriptorSet = Silk.NET.Vulkan.DescriptorSet;
global using VkDescriptorSetLayout = Silk.NET.Vulkan.DescriptorSetLayout;
global using VkFormat = Silk.NET.Vulkan.Format;
global using VkImage = Silk.NET.Vulkan.Image;
global using VkImageView = Silk.NET.Vulkan.ImageView;
global using VkInstance = Silk.NET.Vulkan.Instance;
global using VkPhysicalDevice = Silk.NET.Vulkan.PhysicalDevice;
global using VkPipeline = Silk.NET.Vulkan.Pipeline;
global using VkPipelineLayout = Silk.NET.Vulkan.PipelineLayout;
global using VkPipelineCache = Silk.NET.Vulkan.PipelineCache;
global using VkQueryPool = Silk.NET.Vulkan.QueryPool;
global using VkQueue = Silk.NET.Vulkan.Queue;
global using VkSampler = Silk.NET.Vulkan.Sampler;
global using VkSemaphore = Silk.NET.Vulkan.Semaphore;
global using VkShaderModule = Silk.NET.Vulkan.ShaderModule;
global using VkBufferView = Silk.NET.Vulkan.BufferView;
global using VkSurface = Silk.NET.Vulkan.SurfaceKHR;
global using VkSwapchain = Silk.NET.Vulkan.SwapchainKHR;
