using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace SomeEngine.Generators;

[Generator]
public sealed class AssetCatalogGen : IIncrementalGenerator
{
    private const string ProviderInterfaceName = "SomeEngine.Assets.IAssetProvider";
    private const string ImporterInterfaceName = "SomeEngine.Assets.IAssetImporter";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (spc, compilation) =>
            {
                string source = GenerateCatalog(compilation);
                if (!string.IsNullOrEmpty(source))
                {
                    spc.AddSource("AssetCatalog.g.cs", source);
                }
            });
    }

    private static string GenerateCatalog(Compilation compilation)
    {
        if (!string.Equals(compilation.Assembly.Name, "SomeEngine.Assets", System.StringComparison.Ordinal))
        {
            return string.Empty;
        }

        INamedTypeSymbol? providerInterface = compilation.GetTypeByMetadataName(ProviderInterfaceName);
        INamedTypeSymbol? importerInterface = compilation.GetTypeByMetadataName(ImporterInterfaceName);
        if (providerInterface == null || importerInterface == null)
        {
            return string.Empty;
        }

        ImmutableArray<INamedTypeSymbol> providers = FindRegistrations(compilation.Assembly.GlobalNamespace, providerInterface);
        ImmutableArray<INamedTypeSymbol> importers = FindRegistrations(compilation.Assembly.GlobalNamespace, importerInterface);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace SomeEngine.Assets;");
        sb.AppendLine();
        sb.AppendLine("public static class AssetCatalog");
        sb.AppendLine("{");
        sb.AppendLine("    public static IReadOnlyList<IAssetProvider> CreateProviders()");
        sb.AppendLine("        => new IAssetProvider[]");
        sb.AppendLine("        {");
        foreach (INamedTypeSymbol provider in providers)
        {
            sb.Append("            new ");
            sb.Append(provider.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            sb.AppendLine("(),");
        }
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("    public static IReadOnlyList<IAssetImporter> CreateImporters()");
        sb.AppendLine("        => new IAssetImporter[]");
        sb.AppendLine("        {");
        foreach (INamedTypeSymbol importer in importers)
        {
            sb.Append("            new ");
            sb.Append(importer.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            sb.AppendLine("(),");
        }
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("    public static AssetDatabase CreateDatabase(string projectRoot, string? manifestDirectory = null)");
        sb.AppendLine("        => new(projectRoot, CreateProviders(), CreateImporters(), manifestDirectory);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static ImmutableArray<INamedTypeSymbol> FindRegistrations(INamespaceSymbol ns, INamedTypeSymbol registrationInterface)
    {
        var registrations = ImmutableArray.CreateBuilder<INamedTypeSymbol>();
        CollectRegistrations(ns, registrationInterface, registrations);
        return registrations
            .OrderBy(static symbol => symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), System.StringComparer.Ordinal)
            .ToImmutableArray();
    }

    private static void CollectRegistrations(
        INamespaceSymbol ns,
        INamedTypeSymbol registrationInterface,
        ImmutableArray<INamedTypeSymbol>.Builder registrations)
    {
        foreach (INamespaceSymbol childNamespace in ns.GetNamespaceMembers())
        {
            CollectRegistrations(childNamespace, registrationInterface, registrations);
        }

        foreach (INamedTypeSymbol type in ns.GetTypeMembers())
        {
            CollectRegistrations(type, registrationInterface, registrations);
        }
    }

    private static void CollectRegistrations(
        INamedTypeSymbol type,
        INamedTypeSymbol registrationInterface,
        ImmutableArray<INamedTypeSymbol>.Builder registrations)
    {
        if (IsConcreteRegistration(type, registrationInterface))
        {
            registrations.Add(type);
        }

        foreach (INamedTypeSymbol nestedType in type.GetTypeMembers())
        {
            CollectRegistrations(nestedType, registrationInterface, registrations);
        }
    }

    private static bool IsConcreteRegistration(INamedTypeSymbol type, INamedTypeSymbol registrationInterface)
    {
        if (type.TypeKind != TypeKind.Class || type.IsAbstract || type.IsStatic || type.IsGenericType)
        {
            return false;
        }

        if (!type.AllInterfaces.Any(interfaceType => SymbolEqualityComparer.Default.Equals(interfaceType, registrationInterface)))
        {
            return false;
        }

        return type.InstanceConstructors.Any(static ctor => ctor.Parameters.Length == 0 && ctor.DeclaredAccessibility != Accessibility.Private)
            || type.InstanceConstructors.Length == 0;
    }
}
