using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SomeEngine.Generators;

/// <summary>Generates dense, material-local slots for partial properties on Material types.</summary>
[Generator]
public sealed class MaterialGen : IIncrementalGenerator
{
    private const string MaterialTypeName = "SomeEngine.Assets.Schema.Material";

    private static readonly SymbolDisplayFormat QualifiedTypeFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions:
            SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
            SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (production, compilation) =>
            {
                foreach (MaterialInfo material in Build(compilation))
                    production.AddSource(material.HintName, Emit(material));
            });
    }

    private static ImmutableArray<MaterialInfo> Build(Compilation compilation)
    {
        INamedTypeSymbol? materialBase = compilation.GetTypeByMetadataName(MaterialTypeName);
        if (materialBase is null)
            return [];

        var materials = ImmutableArray.CreateBuilder<MaterialInfo>();
        Collect(compilation.Assembly.GlobalNamespace, materialBase, materials);
        return materials.ToImmutable();
    }

    private static void Collect(
        INamespaceSymbol ns,
        INamedTypeSymbol materialBase,
        ImmutableArray<MaterialInfo>.Builder materials)
    {
        foreach (INamespaceSymbol child in ns.GetNamespaceMembers())
            Collect(child, materialBase, materials);
        foreach (INamedTypeSymbol type in ns.GetTypeMembers())
            Collect(type, materialBase, materials);
    }

    private static void Collect(
        INamedTypeSymbol type,
        INamedTypeSymbol materialBase,
        ImmutableArray<MaterialInfo>.Builder materials)
    {
        if (IsMaterial(type, materialBase))
        {
            ImmutableArray<PropertyInfo> properties = type.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(static property => !property.IsStatic && IsPartialProperty(property))
                .OrderBy(static property => SourcePath(property), StringComparer.Ordinal)
                .ThenBy(static property => SourceStart(property))
                .ThenBy(static property => property.Name, StringComparer.Ordinal)
                .Select(static (property, slot) => new PropertyInfo(
                    property.Name,
                    property.Type.ToDisplayString(QualifiedTypeFormat),
                    property.Type.WithNullableAnnotation(NullableAnnotation.None)
                        .ToDisplayString(QualifiedTypeFormat),
                    AccessibilityText(property.DeclaredAccessibility),
                    property.SetMethod?.IsInitOnly == true,
                    checked((uint)slot)))
                .ToImmutableArray();
            if (!properties.IsDefaultOrEmpty)
            {
                materials.Add(new MaterialInfo(
                    type.ContainingNamespace.IsGlobalNamespace
                        ? string.Empty
                        : type.ContainingNamespace.ToDisplayString(),
                    AccessibilityText(type.DeclaredAccessibility),
                    type.IsSealed,
                    type.Name,
                    Sanitize(type.ToDisplayString()) + ".Material.g.cs",
                    properties));
            }
        }

        foreach (INamedTypeSymbol nested in type.GetTypeMembers())
            Collect(nested, materialBase, materials);
    }

    private static bool IsMaterial(INamedTypeSymbol type, INamedTypeSymbol materialBase)
    {
        for (INamedTypeSymbol? current = type.BaseType; current is not null; current = current.BaseType)
            if (SymbolEqualityComparer.Default.Equals(current, materialBase))
                return true;
        return false;
    }

    private static bool IsPartialProperty(IPropertySymbol property)
        => property.DeclaringSyntaxReferences.Any(reference =>
            reference.GetSyntax() is PropertyDeclarationSyntax syntax &&
            syntax.Modifiers.Any(SyntaxKind.PartialKeyword));

    private static string Emit(MaterialInfo material)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        if (material.Namespace.Length != 0)
        {
            source.Append("namespace ").Append(material.Namespace).AppendLine(";");
            source.AppendLine();
        }

        source.Append(material.Accessibility).Append(' ');
        if (material.IsSealed)
            source.Append("sealed ");
        source.Append("partial class ").Append(material.Name).AppendLine();
        source.AppendLine("{");
        foreach (PropertyInfo property in material.Properties)
        {
            source.Append("    ").Append(property.Accessibility).Append(" partial ")
                .Append(property.Type).Append(' ').Append(property.Name).AppendLine();
            source.AppendLine("    {");
            source.Append("        get => GetSlot<").Append(property.Type).Append(">(")
                .Append(property.Slot).AppendLine("u);");
            source.Append("        ").Append(property.IsInitOnly ? "init" : "set")
                .Append(" => SetSlot(").Append(property.Slot).AppendLine("u, value);");
            source.AppendLine("    }");
            source.AppendLine();
        }

        source.AppendLine("    protected override global::SomeEngine.Assets.Schema.MaterialSlotDefinition[] CreateSlots() =>");
        source.AppendLine("    [");
        foreach (PropertyInfo property in material.Properties)
        {
            source.Append("        new global::SomeEngine.Assets.Schema.MaterialSlotDefinition(")
                .Append(property.Slot).Append("u, \"").Append(Escape(property.Name))
                .Append("\", typeof(").Append(property.TypeOf).AppendLine(")),");
        }
        source.AppendLine("    ];");
        source.AppendLine("}");
        return source.ToString();
    }

    private static string SourcePath(IPropertySymbol property)
        => property.Locations.FirstOrDefault(static location => location.IsInSource)
            ?.SourceTree?.FilePath ?? string.Empty;

    private static int SourceStart(IPropertySymbol property)
        => property.Locations.FirstOrDefault(static location => location.IsInSource)
            ?.SourceSpan.Start ?? int.MaxValue;

    private static string AccessibilityText(Accessibility accessibility)
        => accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "private",
        };

    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string Sanitize(string value)
    {
        var result = new StringBuilder(value.Length);
        foreach (char character in value)
            result.Append(char.IsLetterOrDigit(character) ? character : '_');
        return result.ToString();
    }

    private readonly struct MaterialInfo
    {
        internal MaterialInfo(
            string ns,
            string accessibility,
            bool isSealed,
            string name,
            string hintName,
            ImmutableArray<PropertyInfo> properties)
        {
            Namespace = ns;
            Accessibility = accessibility;
            IsSealed = isSealed;
            Name = name;
            HintName = hintName;
            Properties = properties;
        }

        internal string Namespace { get; }
        internal string Accessibility { get; }
        internal bool IsSealed { get; }
        internal string Name { get; }
        internal string HintName { get; }
        internal ImmutableArray<PropertyInfo> Properties { get; }
    }

    private readonly struct PropertyInfo
    {
        internal PropertyInfo(
            string name,
            string type,
            string typeOf,
            string accessibility,
            bool isInitOnly,
            uint slot)
        {
            Name = name;
            Type = type;
            TypeOf = typeOf;
            Accessibility = accessibility;
            IsInitOnly = isInitOnly;
            Slot = slot;
        }

        internal string Name { get; }
        internal string Type { get; }
        internal string TypeOf { get; }
        internal string Accessibility { get; }
        internal bool IsInitOnly { get; }
        internal uint Slot { get; }
    }
}
