using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace SomeEngine.Generators;

[Generator]
public sealed class MaterialGen : IIncrementalGenerator
{
    private const string BindAttributeName = "SomeEngine.Render.Materials.BindFieldAttribute";
    private const string ScalarAttributeName = "SomeEngine.Render.Materials.ScalarFieldAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (spc, compilation) =>
            {
                foreach (MaterialInfo material in Build(compilation))
                    spc.AddSource($"{material.Name}.Material.g.cs", Emit(material));
            });
    }

    private static ImmutableArray<MaterialInfo> Build(Compilation compilation)
    {
        var materials = ImmutableArray.CreateBuilder<MaterialInfo>();
        Collect(compilation.Assembly.GlobalNamespace, materials);
        return materials.ToImmutable();
    }

    private static void Collect(INamespaceSymbol ns, ImmutableArray<MaterialInfo>.Builder materials)
    {
        foreach (INamespaceSymbol child in ns.GetNamespaceMembers())
            Collect(child, materials);
        foreach (INamedTypeSymbol type in ns.GetTypeMembers())
            Collect(type, materials);
    }

    private static void Collect(INamedTypeSymbol type, ImmutableArray<MaterialInfo>.Builder materials)
    {
        var binds = ImmutableArray.CreateBuilder<FieldInfo>();
        var scalars = ImmutableArray.CreateBuilder<FieldInfo>();

        foreach (ISymbol member in type.GetMembers())
        {
            if (member is not IFieldSymbol and not IPropertySymbol)
                continue;

            string memberType = MemberType(member);
            foreach (AttributeData attribute in member.GetAttributes())
            {
                string? attributeName = attribute.AttributeClass?.ToDisplayString();
                if (attribute.ConstructorArguments.Length != 1
                    || attribute.ConstructorArguments[0].Value is not string fieldName
                    || string.IsNullOrWhiteSpace(fieldName))
                {
                    continue;
                }

                if (string.Equals(attributeName, BindAttributeName, StringComparison.Ordinal))
                    binds.Add(new FieldInfo(member.Name, fieldName, memberType));
                else if (string.Equals(attributeName, ScalarAttributeName, StringComparison.Ordinal))
                    scalars.Add(new FieldInfo(member.Name, fieldName, memberType));
            }
        }

        if (binds.Count != 0 || scalars.Count != 0)
        {
            materials.Add(new MaterialInfo(
                NamespaceOf(type),
                TypeDecl(type),
                type.Name,
                binds.ToImmutable(),
                scalars.ToImmutable()));
        }

        foreach (INamedTypeSymbol nested in type.GetTypeMembers())
            Collect(nested, materials);
    }

    private static string Emit(MaterialInfo material)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (material.Namespace.Length != 0)
        {
            sb.Append("namespace ").Append(material.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append(material.TypeDecl).Append(' ').Append(material.Name).AppendLine();
        sb.AppendLine("{");
        EmitScalars(material, sb);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitScalars(MaterialInfo material, StringBuilder sb)
    {
        sb.AppendLine("    internal partial void WriteFields(global::SomeEngine.Render.Materials.ScalarLayout layout, global::System.Span<byte> payload)");
        sb.AppendLine("    {");
        foreach (FieldInfo field in material.Scalars.OrderBy(static field => field.Name, StringComparer.Ordinal))
            sb.Append("        layout.Write(\"").Append(Escape(field.Name)).Append("\", ").Append(field.Member).AppendLine(", payload);");
        sb.AppendLine("    }");
    }

    private static string MemberType(ISymbol member)
        => member switch
        {
            IFieldSymbol field => field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty),
            IPropertySymbol property => property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty),
            _ => string.Empty,
        };

    private static string NamespaceOf(INamedTypeSymbol type)
        => type.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : type.ContainingNamespace.ToDisplayString();

    private static string TypeDecl(INamedTypeSymbol type)
    {
        string access = type.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            _ => "internal",
        };
        string modifier = type.IsSealed && type.TypeKind == TypeKind.Class ? " sealed" : string.Empty;
        string kind = type.TypeKind == TypeKind.Struct ? "struct" : "class";
        return $"{access}{modifier} partial {kind}";
    }

    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private readonly struct MaterialInfo
    {
        public MaterialInfo(
            string ns,
            string typeDecl,
            string name,
            ImmutableArray<FieldInfo> binds,
            ImmutableArray<FieldInfo> scalars)
        {
            Namespace = ns;
            TypeDecl = typeDecl;
            Name = name;
            Binds = binds;
            Scalars = scalars;
        }

        public string Namespace { get; }
        public string TypeDecl { get; }
        public string Name { get; }
        public ImmutableArray<FieldInfo> Binds { get; }
        public ImmutableArray<FieldInfo> Scalars { get; }
    }

    private readonly struct FieldInfo
    {
        public FieldInfo(string member, string name, string type)
        {
            Member = member;
            Name = name;
            Type = type;
        }

        public string Member { get; }
        public string Name { get; }
        public string Type { get; }
    }
}


