// FlatBuffers schema for Material Instance Asset
// include must come before ALL other declarations
include "common_types.fbs";

namespace SomeEngine.Assets.Schema;

attribute "fs_serializer";
attribute "fs_vector";

table ParamOverride {
    name: string;                         // overridden texture name
    texture_guid: string;
}

table ScalarOverride {
    name: string;                         // overridden scalar param name
    value: ParamValue;                    // new typed value
}

table MaterialInstanceAsset (fs_serializer) {
    asset_guid: string;
    parent_guid: string;
    overrides: [ParamOverride] (fs_vector:"IList");
    scalar_overrides: [ScalarOverride] (fs_vector:"IList");
}

root_type MaterialInstanceAsset;
