<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SomeEngine.Core\SomeEngine.Core.csproj" />
    <ProjectReference Include="..\SomeEngine.Assets\SomeEngine.Assets.csproj" />
    <ProjectReference Include="..\SomeEngine.ECS\SomeEngine.ECS.csproj" />
    <ProjectReference Include="..\SomeEngine.Generators\SomeEngine.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
