<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SomeEngine.Generators\SomeEngine.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\SomeEngine.Assets\SomeEngine.Assets.csproj" />
    <ProjectReference Include="..\SomeEngine.ECS\SomeEngine.ECS.csproj" />
    <ProjectReference Include="..\SomeEngine.ECS.Systems\SomeEngine.ECS.Systems.csproj" />
    <ProjectReference Include="..\SomeEngine.Graphics\SomeEngine.Graphics.csproj" />
    <ProjectReference Include="..\SomeEngine.Render\SomeEngine.Render.csproj" />
    <ProjectReference Include="..\SomeEngine.Render.Cluster\SomeEngine.Render.Cluster.csproj" />
    <ProjectReference Include="..\SomeEngine.RenderGraph\SomeEngine.RenderGraph.csproj" />
    <ProjectReference Include="..\..\external\SlangShaderSharp\src\SlangShaderSharp.csproj" />
  </ItemGroup>
</Project>
